/*
    This file was generated automatically by Alchitry Labs 2.0.52-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/

module alchitry_top (
        input wire clk,
        input wire rst_n,
        output reg [7:0] led,
        output reg ws2812_out,
        output reg [2:0][7:0] io_led,
        output reg [7:0] io_segment,
        output reg [3:0] io_select,
        input wire [3:0] io_button,
        input wire [8:0] cell_switch,
        input wire [2:0][7:0] io_dip
    );
    logic rst;
    logic game_rst;
    localparam CLK_FREQ = 27'd10000000;
    localparam SWITCH_DEBOUNCE_MS = 7'd50;
    localparam _MP_STAGES_2016346879 = 3'h4;
    logic [2:0] clk_div_q = 0;
    logic clk_10m_q = 0;
    logic M_reset_slow_cond_out;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            clk_div_q <= 3'h0;
            clk_10m_q <= 1'b0;
        end else if (clk_div_q == 3'd4) begin
            clk_div_q <= 3'h0;
            clk_10m_q <= ~clk_10m_q;
        end else begin
            clk_div_q <= clk_div_q + 1'b1;
        end
    end

    reset_conditioner #(
        .STAGES(_MP_STAGES_2016346879)
    ) reset_slow_cond (
        .clk(clk_10m_q),
        .in(~rst_n),
        .out(M_reset_slow_cond_out)
    );
    
    
    logic M_start_cond_out;
    logic [8:0] M_cell_switch_cond;
    logic [8:0] M_cell_switch_edge;
    genvar cell_idx;
    
    button_conditioner #(
        .CLK_FREQ(CLK_FREQ),
        .MIN_DELAY(SWITCH_DEBOUNCE_MS),
        .NUM_SYNC(2'd2)
    ) start_cond (
        .clk(clk_10m_q),
        .in(io_button[1'h1]),
        .out(M_start_cond_out)
    );
    
    
    localparam _MP_RISE_570326666 = 1'h1;
    localparam _MP_FALL_570326666 = 1'h0;
    logic M_start_edge_out;
    
    edge_detector #(
        .RISE(_MP_RISE_570326666),
        .FALL(_MP_FALL_570326666)
    ) start_edge (
        .clk(clk_10m_q),
        .in(M_start_cond_out),
        .out(M_start_edge_out)
    );

    generate
        for (cell_idx = 0; cell_idx < 9; cell_idx = cell_idx + 1) begin : gen_cell_switch
            button_conditioner #(
                .CLK_FREQ(CLK_FREQ),
                .MIN_DELAY(SWITCH_DEBOUNCE_MS),
                .NUM_SYNC(2'd2)
            ) cell_cond (
                .clk(clk_10m_q),
                .in(cell_switch[cell_idx]),
                .out(M_cell_switch_cond[cell_idx])
            );

            edge_detector #(
                .RISE(1'b1),
                .FALL(1'b0)
            ) cell_edge (
                .clk(clk_10m_q),
                .in(M_cell_switch_cond[cell_idx]),
                .out(M_cell_switch_edge[cell_idx])
            );
        end
    endgenerate
    
    
    logic [8:0] cell_buttons;
    logic [8:0] M_game_p1_leds;
    logic [8:0] M_game_p2_leds;
    logic M_game_turn_led;
    logic M_game_game_over_led;
    logic M_game_winner_p1;
    logic M_game_winner_p2;
    logic [8:0][1:0] M_game_cell_states;
    logic M_board_display_ws2812_out;
    
    game_datapath game (
        .clk(clk_10m_q),
        .rst(game_rst),
        .slowclk(1'h1),
        .cell_buttons(cell_buttons),
        .start_btn(M_start_edge_out),
        .p1_leds(M_game_p1_leds),
        .p2_leds(M_game_p2_leds),
        .turn_led(M_game_turn_led),
        .game_over_led(M_game_game_over_led),
        .winner_p1(M_game_winner_p1),
        .winner_p2(M_game_winner_p2),
        .cell_states(M_game_cell_states)
    );

    tictactoe_ws2812_display board_display (
        .clk(clk_10m_q),
        .rst(game_rst),
        .cell_states(M_game_cell_states),
        .ws2812_out(M_board_display_ws2812_out)
    );
    
    
    always @* begin
        rst = M_reset_slow_cond_out;
        game_rst = rst | M_start_edge_out;
        led = 8'h0;
        ws2812_out = 1'b0;
        io_led = {8'h0, 8'h0, 8'h0};
        io_segment = 8'h0;
        io_select = 4'h0;
        cell_buttons = M_cell_switch_edge;
        io_led[1'h0] = M_game_p1_leds[3'h7:1'h0];
        led[1'h0] = M_game_p1_leds[4'h8];
        io_led[1'h1] = M_game_p2_leds[3'h7:1'h0];
        led[1'h1] = M_game_p2_leds[4'h8];
        io_led[2'h2][1'h0] = M_game_turn_led;
        io_led[2'h2][1'h1] = M_game_game_over_led;
        io_led[2'h2][2'h2] = M_game_winner_p1;
        io_led[2'h2][2'h3] = M_game_winner_p2;
        io_led[2'h2][3'h6:3'h4] = cell_switch[2:0];
        ws2812_out = M_board_display_ws2812_out;
    end
    
    
endmodule
