/*
    This file was generated automatically by Alchitry Labs 2.0.52-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/

module compare_unit #(
        parameter SIZE = 4'h8
    ) (
        input wire z,
        input wire v,
        input wire n,
        input wire [5:0] alufn,
        output reg cmp
    );
    logic M_mux4_a;
    logic M_mux4_b;
    logic M_mux4_c;
    logic M_mux4_d;
    logic M_mux4_sel1;
    logic M_mux4_sel2;
    logic M_mux4_out;
    
    mux4to1 mux4 (
        .a(M_mux4_a),
        .b(M_mux4_b),
        .c(M_mux4_c),
        .d(M_mux4_d),
        .sel1(M_mux4_sel1),
        .sel2(M_mux4_sel2),
        .out(M_mux4_out)
    );
    
    
    always @* begin
        M_mux4_a = 1'h0;
        M_mux4_b = z;
        M_mux4_c = n ^ v;
        M_mux4_d = (n ^ v) | z;
        M_mux4_sel1 = alufn[1'h1];
        M_mux4_sel2 = alufn[2'h2];
        cmp = M_mux4_out;
    end
    
    
endmodule