/*
    This file was generated automatically by Alchitry Labs 2.0.52-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/

module game_fsm (
        input wire clk,
        input wire rst,
        input wire slowclk,
        input wire rd2_zero,
        input wire rd2_lsb,
        input wire button_press,
        input wire start_btn,
        input wire [3:0] button_index,
        output reg [4:0] out_state,
        output reg cur_turn,
        output reg [2:0] win_rom_idx,
        output reg [3:0] saved_btn_out
    );
    localparam IDLE = 5'h0;
    localparam STORE_P1_MASK = 5'h1;
    localparam STORE_P2_MASK = 5'h2;
    localparam COMBINE_OR = 5'h3;
    localparam VALIDATE_AND = 5'h4;
    localparam BRANCH_VALIDATE = 5'h5;
    localparam PLACE = 5'h6;
    localparam UPDATE_P1 = 5'h7;
    localparam UPDATE_P2 = 5'h8;
    localparam POPCOUNT_MASK = 5'h9;
    localparam CMPEQ_3 = 5'ha;
    localparam BRANCH_POPCOUNT = 5'hb;
    localparam WIN_AND = 5'hc;
    localparam WIN_CMPEQ = 5'hd;
    localparam BRANCH_WIN = 5'he;
    localparam WIN_NEXT = 5'hf;
    localparam SWITCH_TURN = 5'h10;
    localparam GAME_OVER = 5'h11;
    logic [4:0] D_state_d, D_state_q = 1'h0;
    logic D_turn_dff_d, D_turn_dff_q = 1'h0;
    logic [2:0] D_win_idx_d, D_win_idx_q = 1'h0;
    logic [3:0] D_saved_btn_d, D_saved_btn_q = 1'h0;
    always @* begin
        D_state_d = D_state_q;
        D_turn_dff_d = D_turn_dff_q;
        D_win_idx_d = D_win_idx_q;
        D_saved_btn_d = D_saved_btn_q;
        
        out_state = D_state_q;
        cur_turn = D_turn_dff_q;
        win_rom_idx = D_win_idx_q;
        saved_btn_out = D_saved_btn_q;
        D_state_d = D_state_q;
        D_turn_dff_d = D_turn_dff_q;
        D_win_idx_d = D_win_idx_q;
        D_saved_btn_d = D_saved_btn_q;
        if (slowclk) begin
            
            case (D_state_q)
                5'h0: begin
                    if (start_btn) begin
                        D_turn_dff_d = 1'h0;
                        D_win_idx_d = 1'h0;
                    end
                    if (button_press) begin
                        D_saved_btn_d = button_index;
                        D_state_d = 5'h1;
                    end
                end
                5'h1: begin
                    D_state_d = 5'h2;
                end
                5'h2: begin
                    D_state_d = 5'h3;
                end
                5'h3: begin
                    D_state_d = 5'h4;
                end
                5'h4: begin
                    D_state_d = 5'h5;
                end
                5'h5: begin
                    if (rd2_zero) begin
                        D_state_d = 5'h6;
                    end else begin
                        D_state_d = 5'h0;
                    end
                end
                5'h6: begin
                    D_state_d = 5'h7;
                end
                5'h7: begin
                    D_state_d = 5'h8;
                end
                5'h8: begin
                    D_state_d = 5'h9;
                end
                5'h9: begin
                    D_state_d = 5'ha;
                end
                5'ha: begin
                    D_state_d = 5'hb;
                end
                5'hb: begin
                    if (rd2_lsb) begin
                        D_win_idx_d = 1'h0;
                        D_state_d = 5'hc;
                    end else begin
                        D_state_d = 5'h10;
                    end
                end
                5'hc: begin
                    D_state_d = 5'hd;
                end
                5'hd: begin
                    D_state_d = 5'he;
                end
                5'he: begin
                    if (rd2_lsb) begin
                        D_state_d = 5'h11;
                    end else begin
                        D_state_d = 5'hf;
                    end
                end
                5'hf: begin
                    if (D_win_idx_q == 3'h7) begin
                        D_state_d = 5'h10;
                    end else begin
                        D_win_idx_d = (($bits(D_win_idx_q) > $bits(1'h1) ? $bits(D_win_idx_q) : $bits(1'h1)) + 1)'(D_win_idx_q + 1'h1);
                        D_state_d = 5'hc;
                    end
                end
                5'h10: begin
                    D_turn_dff_d = ~D_turn_dff_q;
                    D_state_d = 5'h0;
                end
                5'h11: begin
                    if (start_btn) begin
                        D_turn_dff_d = 1'h0;
                        D_state_d = 5'h0;
                    end
                end
            endcase
        end
    end
    
    
    always @(posedge (clk)) begin
        if ((rst) == 1'b1) begin
            D_state_q <= 1'h0;
            D_turn_dff_q <= 1'h0;
            D_win_idx_q <= 1'h0;
            D_saved_btn_q <= 1'h0;
        end else begin
            D_state_q <= D_state_d;
            D_turn_dff_q <= D_turn_dff_d;
            D_win_idx_q <= D_win_idx_d;
            D_saved_btn_q <= D_saved_btn_d;
        end
    end
endmodule