/*
    This file was generated automatically by Alchitry Labs 2.0.52-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/

module mux2to1 (
        input wire sel,
        input wire a,
        input wire b,
        output reg out
    );
    always @* begin
        out = a;
        if (sel) begin
            out = b;
        end
    end
    
    
endmodule