/*
    This file was generated automatically by Alchitry Labs 2.0.52-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/

module rca #(
        parameter SIZE = 6'h20
    ) (
        input wire [(SIZE)-1:0] a,
        input wire [(SIZE)-1:0] b,
        input wire cin,
        output reg [(SIZE)-1:0] s,
        output reg cout
    );
    logic [31:0] R_4957d4a1_i;
    logic [31:0] RR_4957d4a1_i;
    logic [(SIZE)-1:0] M_fa_a;
    logic [(SIZE)-1:0] M_fa_b;
    logic [(SIZE)-1:0] M_fa_cin;
    logic [(SIZE)-1:0] M_fa_s;
    logic [(SIZE)-1:0] M_fa_cout;
    
    genvar idx_0_1083819411;
    
    generate
        for (idx_0_1083819411 = 0; idx_0_1083819411 < SIZE; idx_0_1083819411 = idx_0_1083819411 + 1) begin: forLoop_idx_0_1083819411
            fa fa (
                .a(M_fa_a[idx_0_1083819411]),
                .b(M_fa_b[idx_0_1083819411]),
                .cin(M_fa_cin[idx_0_1083819411]),
                .s(M_fa_s[idx_0_1083819411]),
                .cout(M_fa_cout[idx_0_1083819411])
            );
        end
    endgenerate
    
    
    always @* begin
        s = 1'h0;
        cout = 1'h0;
        M_fa_a = a;
        M_fa_b = b;
        M_fa_cin[1'h0] = cin;
        for (RR_4957d4a1_i = 0; RR_4957d4a1_i < (($bits(SIZE) > $bits(1'h1) ? $bits(SIZE) : $bits(1'h1)) + 1)'(SIZE - 1'h1); RR_4957d4a1_i = RR_4957d4a1_i + 1) begin
      R_4957d4a1_i = (0) + RR_4957d4a1_i * (1);
            M_fa_cin[(($bits(R_4957d4a1_i) > $bits(1'h1) ? $bits(R_4957d4a1_i) : $bits(1'h1)) + 1)'(R_4957d4a1_i + 1'h1)] = M_fa_cout[R_4957d4a1_i];
        end
        s = M_fa_s;
        cout = M_fa_cout[(($bits(SIZE) > $bits(1'h1) ? $bits(SIZE) : $bits(1'h1)) + 1)'(SIZE - 1'h1)];
    end
    
    
endmodule